import { test, expect } from '@playwright/test'

// Fresh temporary browser contexts only. Block cloud traffic so this suite cannot mutate remote data.
test.beforeEach(async ({ context }) => {
  await context.route('**/*', route => new URL(route.request().url()).hostname.endsWith('.supabase.co') ? route.abort() : route.continue())
})
async function startLocal(page, url = './') {
  await page.goto(url)
  await page.getByRole('button', { name: 'Continue locally' }).click()
  await expect(page.getByRole('heading', { name: 'Workouts', exact: true })).toBeVisible()
}
async function createWorkout(page) {
  await page.getByRole('button', { name: 'New workout', exact: true }).click()
  await page.getByLabel('Workout type', { exact: true }).fill('Independent training')
  await page.getByLabel('New exercise name', { exact: true }).fill('Custom press')
  await page.getByRole('button', { name: 'Add exercise', exact: true }).click()
  await page.getByRole('button', { name: 'Add set', exact: true }).click()
  const first = page.getByRole('group', { name: 'Set 1', exact: true })
  await first.getByLabel('Weight (lb)', { exact: true }).fill('12.25')
  await first.getByLabel('Reps', { exact: true }).fill('7')
  await first.getByLabel('Warmup', { exact: true }).check()
  await first.getByLabel('Completed', { exact: true }).check()
  await first.getByText('Set notes', { exact: true }).first().click()
  await first.getByLabel('Set notes', { exact: true }).fill('Warmup note')
  await page.getByRole('button', { name: 'Add set', exact: true }).click()
  const second = page.getByRole('group', { name: 'Set 2', exact: true })
  await second.getByLabel('Weight (lb)', { exact: true }).fill('27.5')
  await second.getByLabel('Reps', { exact: true }).fill('3')
  await second.getByText('Set notes', { exact: true }).first().click()
  await second.getByLabel('Set notes', { exact: true }).fill('Working note')
  await expect(page.getByRole('status')).toContainText('Editor draft saved')
}

test('native workout workflow: distinct sets, draft reload, completion, safe completed edits and legacy history', async ({ page }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await startLocal(page)
  await createWorkout(page)
  const url = page.url()
  await page.reload()
  await expect(page.getByRole('status')).toContainText('Resumed local editor draft')
  const first = page.getByRole('group', { name: 'Set 1', exact: true })
  const second = page.getByRole('group', { name: 'Set 2', exact: true })
  await expect(first.getByLabel('Weight (lb)', { exact: true })).toHaveValue('12.25')
  await expect(second.getByLabel('Weight (lb)', { exact: true })).toHaveValue('27.5')
  await first.getByText('Set notes', { exact: true }).first().click()
  await second.getByText('Set notes', { exact: true }).first().click()
  await expect(first.getByLabel('Set notes', { exact: true })).toHaveValue('Warmup note')
  await expect(second.getByLabel('Set notes', { exact: true })).toHaveValue('Working note')
  await page.getByRole('button', { name: 'Complete workout', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  await expect(second.getByLabel('Completed', { exact: true })).not.toBeChecked()
  await second.getByLabel('Weight (lb)', { exact: true }).fill('31.75')
  await page.getByRole('button', { name: 'Save completed workout changes' }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  await page.reload()
  await expect(second.getByLabel('Weight (lb)', { exact: true })).toHaveValue('31.75')
  await page.evaluate(async () => {
    const { db } = await import('/JorrelWorksOut/src/lib/db.js')
    await db.sessions.put({ id: 'legacy-session', user_id: 'local-user', date: '2020-01-01', type: 'Legacy day', is_complete: true })
    await db.liftResults.put({ id: 'legacy-result', session_id: 'legacy-session', exercise_name: 'Historical lift', set_weights: [10, 20], partial_reps: [8, 6], notes: 'Preserved legacy note' })
  })
  await page.getByRole('link', { name: 'Workouts', exact: true }).click()
  await page.getByRole('link', { name: /Legacy day/ }).click()
  await page.getByText('Historical lift — unknown lb', { exact: true }).click()
  await expect(page.getByText('Preserved legacy note', { exact: true })).toBeVisible()
  await expect(page.getByText('[10,20]', { exact: true })).toBeVisible()
  await page.goto(url)
  await expect(page.getByLabel('Workout type', { exact: true })).toHaveValue('Independent training')
  expect(await page.locator('style, link[rel="stylesheet"], [style]').count()).toBe(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 320, height: 700 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('exercise history ignores hover and toggles by click or keyboard without changing sets', async ({ page }) => {
  await startLocal(page)
  await page.evaluate(async () => {
    const { db } = await import('/JorrelWorksOut/src/lib/db.js')
    await db.sessions.bulkPut([
      { id: 'past', user_id: 'local-user', date: '2020-01-01', is_complete: true },
      { id: 'private-past', user_id: 'another-user', date: '2020-01-02', is_complete: true },
    ])
    await db.liftResults.bulkPut([
      { id: 'past-result', session_id: 'past', exercise_name: 'Bench Press', set_weights: [100, 110], partial_reps: [8, 6], notes: 'Paused reps' },
      { id: 'private-result', session_id: 'private-past', exercise_name: 'Bench Press', set_weights: [999], partial_reps: [99], notes: 'Private note' },
    ])
  })
  await page.getByRole('button', { name: 'New workout', exact: true }).click()
  await page.getByLabel('New exercise name', { exact: true }).fill('Bench Press')
  await page.getByRole('button', { name: 'Add exercise', exact: true }).click()
  const summary = page.locator('summary').filter({ hasText: 'Recent history: Bench Press' })
  const panel = page.locator('details').filter({ has: summary })
  await summary.hover()
  await expect(panel).not.toHaveAttribute('open', '')
  await summary.click()
  await expect(panel).toHaveAttribute('open', '')
  await expect(panel.getByText('Set 2: 110 lb × 6 reps', { exact: true })).toBeVisible()
  await expect(panel.getByText('Exercise notes: Paused reps')).toBeVisible()
  await expect(panel).not.toContainText('Private note')
  await page.getByRole('heading', { name: 'Workout', exact: true }).hover()
  await expect(panel).toHaveAttribute('open', '')
  await summary.click()
  await expect(panel).not.toHaveAttribute('open', '')
  await summary.click()
  await expect(panel).toHaveAttribute('open', '')
  await summary.focus()
  await page.keyboard.press('Escape')
  await expect(panel).not.toHaveAttribute('open', '')
  await page.keyboard.press('Enter')
  await expect(panel).toHaveAttribute('open', '')
  await expect(page.getByRole('group', { name: 'Set 1', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Bench Press')
  expect(await page.locator('style, link[rel="stylesheet"], [style]').count()).toBe(0)
})

test.describe('touch history', () => {
  test.use({ hasTouch: true, isMobile: true })
  test('tap toggles history without requiring hover', async ({ page }) => {
    await startLocal(page)
    await page.getByRole('button', { name: 'New workout', exact: true }).tap()
    await page.getByLabel('New exercise name', { exact: true }).fill('New movement')
    await page.getByRole('button', { name: 'Add exercise', exact: true }).tap()
    const summary = page.locator('summary').filter({ hasText: 'Recent history: New movement' })
    const panel = page.locator('details').filter({ has: summary })
    await summary.tap()
    await expect(panel.getByText('No previous completed workouts for this exercise.')).toBeVisible()
    await summary.tap()
    await expect(panel).not.toHaveAttribute('open', '')
  })
})

test('native progress explorer shows saved history and filters without CSS', async ({ page }) => {
  await startLocal(page)
  await createWorkout(page)
  await page.getByRole('button', { name: 'Complete workout', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  await page.getByRole('link', { name: 'Progress', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Progress', exact: true })).toBeVisible()
  await page.getByLabel('Include warmup sets').check()
  await expect(page.getByRole('cell', { name: '85.75', exact: true }).first()).toBeVisible()
  await expect(page.locator('meter')).toHaveCount(1)
  await page.getByLabel('Metric', { exact: true }).selectOption('weight')
  await expect(page.getByRole('cell', { name: '12.25', exact: true }).first()).toBeVisible()
  await page.getByLabel('From date', { exact: true }).fill('2099-01-01')
  await expect(page.getByText('No completed sets found for this selection.')).toBeVisible()
  await page.getByRole('button', { name: 'All dates' }).click()
  await expect(page.locator('meter')).toHaveCount(1)
  expect(await page.locator('style, link[rel="stylesheet"], [style]').count()).toBe(0)
})

test('exercise picker includes history and supports entirely new movements', async ({ page }) => {
  await startLocal(page)
  await createWorkout(page)
  await page.getByRole('button', { name: 'Complete workout', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  await page.getByRole('link', { name: 'Workouts', exact: true }).click()
  await page.getByRole('button', { name: 'New workout', exact: true }).click()
  await page.getByLabel('Previous exercises and catalog').selectOption('Custom press')
  await page.getByRole('button', { name: 'Add selected exercise', exact: true }).click()
  await expect(page.getByLabel('Exercise name', { exact: true })).toHaveValue('Custom press')
  await page.getByLabel('New exercise name', { exact: true }).fill('Brand new movement')
  await page.getByRole('button', { name: 'Add exercise', exact: true }).click()
  await expect(page.getByLabel('Exercise name', { exact: true }).nth(1)).toHaveValue('Brand new movement')
})

test('runs, catalog and raw markdown plans are usable from top-level navigation', async ({ page }) => {
  await startLocal(page)
  await page.getByRole('link', { name: 'Runs', exact: true }).click()
  await page.getByRole('button', { name: 'New run', exact: true }).click()
  await page.getByLabel('Distance (miles)', { exact: true }).fill('3.25')
  await page.getByLabel('Duration (seconds)', { exact: true }).fill('1500')
  await page.getByText('Optional fields', { exact: true }).click()
  await page.getByLabel('Average heart rate (bpm)', { exact: true }).fill('145')
  await page.getByLabel('Notes', { exact: true }).fill('Run note')
  await page.getByRole('button', { name: 'Save record', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  await page.reload()
  await expect(page.getByLabel('Distance (miles)', { exact: true })).toHaveValue('3.25')
  await page.getByRole('link', { name: 'Exercise catalog', exact: true }).click()
  await page.getByRole('button', { name: 'New exercise', exact: true }).click()
  await page.getByLabel('Name', { exact: true }).fill('Not a template')
  await page.getByRole('button', { name: 'Save record', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  await page.getByRole('link', { name: 'Training plans', exact: true }).click()
  await page.getByRole('button', { name: 'New training plan', exact: true }).click()
  await page.getByLabel('Title', { exact: true }).fill('A plan')
  await page.getByLabel('Raw markdown', { exact: true }).fill('# Week\n\n- **Keep raw**')
  await page.getByRole('button', { name: 'Save record', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  await page.reload()
  await expect(page.getByLabel('Raw markdown', { exact: true })).toHaveValue('# Week\n\n- **Keep raw**')
  await page.getByRole('link', { name: 'Account / data', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Export this account/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toContain('local-user')
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await page.getByRole('button', { name: 'Continue locally', exact: true }).click()
  await page.getByRole('link', { name: 'Runs', exact: true }).click()
  await expect(page.getByRole('link', { name: /3.25 miles/ })).toBeVisible()
})

test('production service worker precaches the reset and resumes a draft after offline reload', async ({ page, context }) => {
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await startLocal(page, 'http://127.0.0.1:4173/JorrelWorksOut/')
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise(resolve => navigator.serviceWorker.addEventListener('controllerchange', resolve, { once: true }))
  })
  await createWorkout(page)
  await page.evaluate(async () => {
    await caches.open('jorrel-works-out-v1')
    await caches.open('unrelated-app-cache')
    const registration = await navigator.serviceWorker.getRegistration()
    await registration.unregister()
  })
  await page.reload()
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise(resolve => navigator.serviceWorker.addEventListener('controllerchange', resolve, { once: true }))
  })
  await expect.poll(() => page.evaluate(() => caches.keys())).not.toContain('jorrel-works-out-v1')
  expect(await page.evaluate(() => caches.keys())).toContain('unrelated-app-cache')
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('status')).toContainText('Resumed local editor draft')
  await expect(page.getByRole('group', { name: 'Set 2', exact: true }).getByLabel('Weight (lb)', { exact: true })).toHaveValue('27.5')
  await page.getByRole('button', { name: 'Complete workout', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  expect(errors).toEqual([])
})

test('cached account opens offline after expiry; offline signout removes identity but retains owned data and queue', async ({ page, context }) => {
  await startLocal(page, 'http://127.0.0.1:4173/JorrelWorksOut/')
  await page.evaluate(async () => {
    await navigator.serviceWorker.ready
    if (!navigator.serviceWorker.controller) await new Promise(resolve => navigator.serviceWorker.addEventListener('controllerchange', resolve, { once: true }))
    // Synthetic prior authenticated identity, never a real token or account.
    localStorage.setItem('jwo.accountAccess', JSON.stringify({ mode: 'account', user: { id: 'test-account-a', email: 'a@example.test' } }))
    localStorage.removeItem('jwo.localMode')
    localStorage.setItem('sb-gvazsjdtrebpzcuhcrek-auth-token', JSON.stringify({
      access_token: 'expired-test-token', refresh_token: 'test-only', expires_at: 1,
      user: { id: 'test-account-a', email: 'a@example.test' },
    }))
    const database = await new Promise((resolve, reject) => {
      const request = indexedDB.open('sl5x5')
      request.onsuccess = () => resolve(request.result)
      request.onerror = () => reject(request.error)
    })
    await new Promise((resolve, reject) => {
      const tx = database.transaction('sessions', 'readwrite')
      tx.objectStore('sessions').put({ id: 'other-account-session', user_id: 'test-account-b', date: '2020-01-01', type: 'Other account private workout', is_complete: true })
      tx.oncomplete = resolve
      tx.onerror = () => reject(tx.error)
    })
    database.close()
  })
  await context.setOffline(true)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Workouts', exact: true })).toBeVisible()
  await expect(page.getByText(/Other account private workout/)).toHaveCount(0)
  await createWorkout(page)
  await page.getByRole('button', { name: 'Complete workout', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Saved on this device')
  await page.getByRole('link', { name: 'Account / data', exact: true }).click()
  await expect(page.getByText('Local access to a@example.test. Sign in to renew cloud authorization.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  expect(await page.evaluate(() => localStorage.getItem('jwo.accountAccess'))).toBe('{"mode":"signed-out"}')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  await expect(page.getByText(/Local access to a@example.test/)).toHaveCount(0)
  const saved = await page.evaluate(async () => {
    const database = await new Promise(resolve => {
      const request = indexedDB.open('sl5x5')
      request.onsuccess = () => resolve(request.result)
    })
    const rows = await Promise.all(['sessions', 'syncQueue'].map(table => new Promise(resolve => {
      const request = database.transaction(table).objectStore(table).getAll()
      request.onsuccess = () => resolve(request.result)
    })))
    database.close()
    return rows
  })
  expect(saved[0].filter(row => row.user_id === 'test-account-a')).toHaveLength(1)
  expect(saved[0].filter(row => row.user_id === 'test-account-b')).toHaveLength(1)
  expect(saved[1].filter(row => row.user_id === 'test-account-a' && row.entity === 'mutation')).toHaveLength(1)
  await page.getByRole('button', { name: 'Continue locally', exact: true }).click()
  await page.getByRole('link', { name: 'Workouts', exact: true }).click()
  await expect(page.getByText('No workouts saved for this account.', { exact: true })).toBeVisible()
})
